# Generated by Django 4.2 on 2023-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('secondname', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('time', models.CharField(max_length=150, null=True)),
                ('service', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review2Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('usersphoto', models.ImageField(max_length=150, null=True, upload_to='')),
                ('date', models.CharField(max_length=150, null=True)),
                ('estimation', models.IntegerField(max_length=150, null=True)),
                ('body', models.CharField(max_length=1500, null=True)),
                ('master', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('usersphoto', models.ImageField(max_length=150, null=True, upload_to='')),
                ('date', models.CharField(max_length=150, null=True)),
                ('estimation', models.IntegerField(max_length=150, null=True)),
                ('body', models.CharField(max_length=1500, null=True)),
            ],
        ),
    ]
