# Generated by Django 4.2 on 2024-03-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='userPhotos/%Y/%m/%d'),
        ),
    ]
