# Generated by Django 4.2 on 2023-10-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review2master',
            name='usersphoto',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='usersphoto',
        ),
    ]
