# Generated by Django 4.2.7 on 2023-12-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_master_category_alter_service_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review2Master',
            new_name='ReviewToMaster',
        ),
    ]
