# Generated by Django 4.2.7 on 2023-12-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_master_name_alter_master_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.service'),
        ),
    ]
