# Generated by Django 4.2 on 2023-12-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
